<?php

/**
 * @file
 * Twitter API integration.
 */

/**
 * Implements hook_theme().
 */
function twitter_api_theme($existing, $type, $theme, $path) {
  return [
    'twitter_api__tweet' => [
      'variables' => ['tweet' => []],
      'path' => $path . '/templates',
      'template' => 'twitter-api--tweet',
    ],
    'twitter_api__tweet_list' => [
      'variables' => ['tweets' => []],
      'path' => $path . '/templates',
      'template' => 'twitter-api--tweet-list',
    ],
  ];
}
